packages:
  - "packages/*"
  - "examples/*"

minimumReleaseAge: 10080 # 7 days
frozenLockfile: true

overrides:
  "@durable-streams/client": 0.1.0

catalog:
  "@durable-streams/server-conformance-tests": 0.1.4
  vitest: 4.1.8
  wrangler: 4.97.0
